/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Betuyaku
 */
public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jWelcome = new javax.swing.JLabel();
        jRequirements = new javax.swing.JLabel();
        jCards = new javax.swing.JLabel();
        jOptions = new javax.swing.JLabel();
        jRentButton = new javax.swing.JButton();
        jReturnButton = new javax.swing.JButton();
        jRedBackground = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jCart = new javax.swing.JMenuItem();
        jExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jWelcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jWelcome.setText("WELCOME TO XTRA-VISION RENTAL KIOSK");
        getContentPane().add(jWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jRequirements.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRequirements.setForeground(new java.awt.Color(255, 255, 255));
        jRequirements.setText("NO membership or sing-up required.");
        getContentPane().add(jRequirements, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jCards.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCards.setForeground(new java.awt.Color(255, 255, 255));
        jCards.setText("CREDIT and DEBIT Card Accepted!");
        getContentPane().add(jCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jOptions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jOptions.setForeground(new java.awt.Color(255, 255, 255));
        jOptions.setText("Please select your option:");
        getContentPane().add(jOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jRentButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRentButton.setText("RENT");
        jRentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jRentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 90, 40));

        jReturnButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jReturnButton.setText("RETURN");
        getContentPane().add(jReturnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 90, 40));

        jRedBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/redBackground.jpg"))); // NOI18N
        jRedBackground.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jRedBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 509, 360));

        jMenuFile.setText("File");

        jCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/icons/baseline_shopping_cart_black_24dp.png"))); // NOI18N
        jCart.setText("Cart");
        jMenuFile.add(jCart);

        jExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/icons/baseline_exit_to_app_black_24dp.png"))); // NOI18N
        jExit.setText("Exit");
        jMenuFile.add(jExit);

        jMenuBar.add(jMenuFile);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCards;
    private javax.swing.JMenuItem jCart;
    private javax.swing.JMenuItem jExit;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JLabel jOptions;
    private javax.swing.JLabel jRedBackground;
    private javax.swing.JButton jRentButton;
    private javax.swing.JLabel jRequirements;
    private javax.swing.JButton jReturnButton;
    private javax.swing.JLabel jWelcome;
    // End of variables declaration//GEN-END:variables
}
