
package View;

import Controller.MovieControl;
import DAO.Connect;
import Model.MovieModel;
import Model.MoviesTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ReturnMovieView extends javax.swing.JFrame {
    private int orderId;
    /**
     * Creates new form ReturnMovieView
     */
    public ReturnMovieView(int id) {
        this.orderId = id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReturn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReturn = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblReturn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblReturn.setText("MOVIES TO RETURN:");

        tblReturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReturnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReturn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReturn)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblReturn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        addMoviesToView();
    }//GEN-LAST:event_formWindowOpened

    private void tblReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReturnMouseClicked
     int row = tblReturn.getSelectedRow();
      MovieModel movieId = (MovieModel)tblReturn.getValueAt(row, 0);
      int i = JOptionPane.showConfirmDialog(this,"return?","", JOptionPane.YES_NO_OPTION);
      if (i == 0){
          returnMovie(movieId.getIdMovie());
      }
    }//GEN-LAST:event_tblReturnMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReturn;
    private javax.swing.JTable tblReturn;
    // End of variables declaration//GEN-END:variables
    void addMoviesToView(){
        
        //add movies into tblReturn
       
        MovieModel[] movies = getMoviesFromOrder();
        MoviesTableModel model = new MoviesTableModel(movies);

        tblReturn.setModel(model);
        tblReturn.getColumnModel().getColumn(0).setWidth(0);
        tblReturn.getColumnModel().getColumn(0).setMinWidth(0);
        tblReturn.getColumnModel().getColumn(0).setMaxWidth(0);

        tblReturn.repaint();  
    }

    private MovieModel[] getMoviesFromOrder() {
        ArrayList<MovieModel> movies = new ArrayList<>();
                
       try{
            Connection con = Connect.getConnection();
            //SQL query
            String query = "SELECT Movie.idMovie, Movie.title, Movie.year, Category.name as category, \n" +
                    "Category.type ,Movie.statusMovie FROM Movie \n" +
                    "inner join Category  on Movie.idCategory = Category.id \n" +
                    "inner join OrderItem oi on Movie.idMovie = oi.OrderMovieId\n" +
                    "WHERE oi.OrderId = "+orderId;
            Statement comm = con.createStatement(); // to excute the Database command without any parameters
            ResultSet result = comm.executeQuery(query);
            while(result.next()){
                if(result.getString(6).equalsIgnoreCase("u")){
                   //create the object to populate the table
                    MovieModel movie = new MovieModel(result.getInt(1),result.getString(2),
                            result.getString(4), result.getInt(3));
                    //add the array into the object
                    movies.add(movie);
                }    
            }
            
       }catch(Exception e){
       
       }
        return movies.toArray(new MovieModel[movies.size()]);
    }  
    
 

    private void returnMovie(int id) {
        try{
            Connection con = Connect.getConnection();
            //SQL query
            String query = "update Movie set statusMovie = 'a' where idMovie = "+id;
                    
            Statement comm = con.createStatement(); // to excute the Database command without any parameters
            comm.execute(query);
            
            
       }catch(Exception e){
       
       }
       addMoviesToView();
        
        
        
       
    }
    
}

